In [2]:
import numpy as np

In [3]:
# Ex 1
print("Printing array \n")
a = np.random.rand(4,2)
print(a)
print("\n")

print(a.shape,"\n", a.ndim)


Printing array 

[[0.47464198 0.67092775]
 [0.74340051 0.91953827]
 [0.48119246 0.61259517]
 [0.92006371 0.74302385]]


(4, 2) 
 2


In [4]:
# ex 2
a = np.arange(100,200,10).reshape(5,2)
a

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [5]:
# ex 3
sampleArray = np.array([[11,22,33],[44,55,66],[77,88,99]])
print(sampleArray,"\n")
sampleArray[:, 2:].flatten()

[[11 22 33]
 [44 55 66]
 [77 88 99]] 



array([33, 66, 99])

In [6]:
# ex 4
sampleArray = np.array([[3,6,9,12],[15,18,21,24],[27,30,33,36],[39,42,45,48],[51,54,57,60]])
a = sampleArray
a[0::2,1::2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [7]:
# ex 5
arrayOne = np.array([[5,6,9],[21,18,27]])
arrayTwo = np.array([[15,33,24],[4,7,1]])
result = arrayOne +arrayTwo
result
result **2


array([[ 400, 1521, 1089],
       [ 625,  625,  784]])

In [8]:
# ex 6
res = np.arange(10,34,1).reshape((8,3))
res
np.vsplit(res,4)

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [9]:
# ex 7
a = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
a

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [10]:
# case 1
a_new = a
b = np.argsort(a[1])
b_sorted = a_new[:,b]
b_sorted

array([[73, 43, 34],
       [12, 22, 82],
       [66, 94, 53]])

In [11]:
# case 2
c_new = a
c = np.argsort(a[:,1])
c_sorted = c_new[c]
c_sorted

array([[82, 22, 12],
       [34, 43, 73],
       [53, 94, 66]])

In [12]:
# ex 8
a = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
a
amin = np.min(a, axis = 1)
print(amin)
amax = np.max(a,axis = 0)
print(amax)

[34 12 53]
[82 94 73]


In [13]:
# ex 9
a = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
newColumn = np.array([[10, 10, 10]])
print(a)
a = np.delete(a, 1, axis=1)
print(a)
a = np.insert(a, 1, newColumn, axis=1)
print(a)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[34 73]
 [82 12]
 [53 66]]
[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [14]:
np.arange(4,16,3)

array([ 4,  7, 10, 13])